// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_JoxBixQueh_EytlopOM7M3Uw8spsVzg',
    appId: '1:279128342664:web:ece457397f3872aeb19f3d',
    messagingSenderId: '279128342664',
    projectId: 'profiscal-app',
    authDomain: 'profiscal-app.firebaseapp.com',
    storageBucket: 'profiscal-app.firebasestorage.app',
    measurementId: 'G-Z7K6R338WM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgVdv85n6OgXT91w8u6uL6wTHgXN9K-zk',
    appId: '1:279128342664:android:2e6173f30accb188b19f3d',
    messagingSenderId: '279128342664',
    projectId: 'profiscal-app',
    storageBucket: 'profiscal-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBoceVFSKgBJbbn-sEhZ6SdJ64sBcu-bg',
    appId: '1:279128342664:ios:7390c8ad4206e122b19f3d',
    messagingSenderId: '279128342664',
    projectId: 'profiscal-app',
    storageBucket: 'profiscal-app.firebasestorage.app',
    iosBundleId: 'com.example.profiscal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBoceVFSKgBJbbn-sEhZ6SdJ64sBcu-bg',
    appId: '1:279128342664:ios:7390c8ad4206e122b19f3d',
    messagingSenderId: '279128342664',
    projectId: 'profiscal-app',
    storageBucket: 'profiscal-app.firebasestorage.app',
    iosBundleId: 'com.example.profiscal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_JoxBixQueh_EytlopOM7M3Uw8spsVzg',
    appId: '1:279128342664:web:024c40a2af8bb4ddb19f3d',
    messagingSenderId: '279128342664',
    projectId: 'profiscal-app',
    authDomain: 'profiscal-app.firebaseapp.com',
    storageBucket: 'profiscal-app.firebasestorage.app',
    measurementId: 'G-E6WWZVN15V',
  );
}
